/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package naivebayesxcertaintyfactor;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yaseen Ameer
 */
public class data_pelamar extends javax.swing.JFrame {
 

    /**
     * Creates new form NewSignin
     */
    public data_pelamar() {
        
        initComponents();
        koneksi_database();
        kosongkan_text();
        AutoNumber();
        tampil_data();
        view_pelamar("SELECT * FROM data_pelamar");
        this.setLocationRelativeTo(null);
 
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_inven5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_jabatan = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        cmb_cari = new javax.swing.JComboBox<>();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        kode_pelamar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        asal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jLabel_inven5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel_inven5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_inven5.setText("Input Data pelamar");
        jPanel1.add(jLabel_inven5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 490, 50));

        jScrollPane1.setForeground(new java.awt.Color(103, 170, 22));

        tabel_jabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_jabatan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 1100, 170));

        txtcari.setForeground(new java.awt.Color(0, 0, 153));
        txtcari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcariCaretUpdate(evt);
            }
        });
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 310, 30));

        btn_exit.setBackground(new java.awt.Color(204, 0, 0));
        btn_exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(0, 0, 153));
        btn_exit.setText("X");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 50, 30));

        btn_delete.setForeground(new java.awt.Color(0, 0, 153));
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, 30));

        btn_update.setForeground(new java.awt.Color(0, 0, 153));
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 30));

        cmb_cari.setForeground(new java.awt.Color(0, 0, 153));
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Pelamar", "Nama" }));
        cmb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_cariActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 30));

        btn_cancel.setForeground(new java.awt.Color(0, 0, 153));
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Cari Berdasarkan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 30));

        btn_save.setForeground(new java.awt.Color(0, 0, 153));
        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 30));

        nama.setForeground(new java.awt.Color(0, 0, 153));
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 310, 30));

        kode_pelamar.setForeground(new java.awt.Color(0, 0, 153));
        kode_pelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_pelamarActionPerformed(evt);
            }
        });
        kode_pelamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kode_pelamarKeyPressed(evt);
            }
        });
        jPanel1.add(kode_pelamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Kode Pelamar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Nama Pelamar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, 30));

        menu1.setBackground(new java.awt.Color(0, 153, 153));
        menu1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(21, 25, 28));
        menu1.setText("Menu");
        menu1.setBorder(null);
        menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu1.setFocusPainted(false);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 80, 30));

        asal.setForeground(new java.awt.Color(0, 0, 153));
        asal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asalActionPerformed(evt);
            }
        });
        jPanel1.add(asal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 540, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Asal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcariCaretUpdate
        String kategori = cmb_cari.getSelectedItem().toString();
        String vkategori;
        if(kategori=="Kode Pelamar"){
            vkategori ="kode_pelamar";
        }else if(kategori=="Nama"){
            vkategori ="nama";
        }else{
            vkategori ="kode_pelamar";
        }
        view_pelamar ("SELECT * FROM data_pelamar WHERE "+vkategori+" LIKE '%"+txtcari.getText()+"%' ");
    }//GEN-LAST:event_txtcariCaretUpdate

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            sql = "DELETE FROM data_pelamar WHERE kode_pelamar='"+kode_pelamar.getText()+"' ";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Terhapus...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }

        if(kode_pelamar.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode Jabatan Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "delete FROM data_pelamar where kode_pelamar='"+kode_pelamar.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Dihapus !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal !"+e);
            }
            kosongkan_text();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            sql = "UPDATE data_pelamar SET nama='"+nama.getText()+
            "' WHERE kode_pelamar='" + kode_pelamar.getText()+"'";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Sukses...!");
            kosongkan_text();
            AutoNumber();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal...!"+e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void cmb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cariActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        kosongkan_text();
        AutoNumber();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            sql = "INSERT INTO data_pelamar VALUES ('"+kode_pelamar.getText()+
            "','"+nama.getText()+
            "','"+asal.getText()+
            
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan...");
            kosongkan_text();
            AutoNumber();
            stat.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal..."+e);
        }

        if(kode_pelamar.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Maaf, Kode jabatan Tolong Di Isi !",
                "Informasi Penting",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                sql = "update data_pelamar set nama='"+nama.getText()+
                "' where kode_pelamar='"+kode_pelamar.getText()+"'";
                stat=con.createStatement();
                stat.execute(sql);
                JOptionPane.showMessageDialog(rootPane, "Data Sudah Diupdate !");
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Diupdate !"+e);
            }
            kosongkan_text();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void kode_pelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_pelamarActionPerformed
     
    }//GEN-LAST:event_kode_pelamarActionPerformed

    private void kode_pelamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_pelamarKeyPressed
       
    }//GEN-LAST:event_kode_pelamarKeyPressed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        menu fa = new menu();
        fa.setLocationRelativeTo(null);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void asalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_pelamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_pelamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_pelamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_pelamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_pelamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asal;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_cari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_inven5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kode_pelamar;
    private javax.swing.JButton menu1;
    private javax.swing.JTextField nama;
    private javax.swing.JTable tabel_jabatan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

   private Connection con;
private Statement stat;
private ResultSet rs;
private String sql;

private void koneksi_database(){
try {
    Class.forName("com.mysql.jdbc.Driver");
    System.out.println("Driver Ditemukan...");
    try {
        String url = "jdbc:mysql://localhost:3306/skripsi?user=root&password=";
        con = DriverManager.getConnection(url);
        System.out.println("Terkoneksi...");
    } catch (SQLException e){
        System.err.println("Tidak Terkoneksi...");
    }
} catch (ClassNotFoundException e) {
    System.err.println("Driver Tidak Ada...");
}
}

private void kosongkan_text() {  
nama.setText("");
asal.setText("");
kode_pelamar.requestFocus();
}

private void AutoNumber(){
try {
sql  = "SELECT MAX(RIGHT(kode_pelamar,4)) AS no_auto FROM data_pelamar";
stat = con.createStatement();
rs   = stat.executeQuery(sql);
if(rs.next()){
String no_auto, nol_plus;
int p;
no_auto = Integer.toString(rs.getInt(1)+1);
p = no_auto.length();
nol_plus = "";
for(int i=1;i<=4-p;i++){
nol_plus = nol_plus + "0";    
}
kode_pelamar.setText("P"+nol_plus+no_auto);
}
} catch (Exception e) {
    kode_pelamar.setText("P001");    
}          
}

private void tampil_data(){
try {
    sql  = "SELECT * FROM data_pelamar WHERE kode_pelamar='"+kode_pelamar.getText()+"'";
    stat = con.createStatement();
    rs   = stat.executeQuery(sql);
    if(rs.next()){
    nama.setText(rs.getString("nama"));
    
    btn_update.setEnabled(true);
    btn_delete.setEnabled(true);
    btn_save.setEnabled(false);
    } else{
    kosongkan_text();
    }
    rs.close();
    stat.close();
    }
catch (Exception e) {
}
}


private void view_pelamar(String sql){
Object[] header = {"Kode Pelamar","Nama Pelamar","Asal"};
DefaultTableModel tabel = new DefaultTableModel(null, header);
tabel_jabatan.setModel(tabel);
try {
  stat = con.createStatement();
  rs = stat.executeQuery(sql);
 
  while (rs.next()){
  String[] Data = {
      
      rs.getString("kode_pelamar"),
      rs.getString("nama"),
      rs.getString("asal"),
      
   
  };  
  tabel.addRow(Data);
 
  }
 
  tabel_jabatan.getColumnModel().getColumn(0).setPreferredWidth(50);
  tabel_jabatan.getColumnModel().getColumn(1).setPreferredWidth(200);
  tabel_jabatan.getColumnModel().getColumn(2).setPreferredWidth(200);
 

  
} catch (Exception e) {
  System.err.println (e);
}
}

}
